### ISSUE TITLE
To-dos for minimum features

### ISSUE THREAD

**Issue by meltedice** [meltedice/todorokite#1]
* [x] List minimum features up
* [x] Draw rough mock-up
* [x] Setup API documentation #2
* [x] Write `list` api documentation #2 
* [x] Convert `list` API documentation #2 
* [x] Setup mock server #2 
* [x] Client: Setup a react app #3 
    * [x] Generate a skelton app #3 
    * [x] Add react-bootstrap #3 
    * [x] Add redux #4 
    * [x] Add react-redux-router #4 
* [x] Client: Display `list` (with embedded data) #5 
* [x] Client: Fetch `list` data via API #5
* [x] Server: Setup a rails app #11 
    * [x] Generate a skelton app
    * [x] Setup databases
    * [x] Add `list` endpoint
    * [x] Add specs
* [x] `new` / `create` feature #12 
    * [x] API document and mock
    * [x] Client
    * [x] Server
* [x] `edit` / `update` feature #14 
    * [x] API document and mock
    * [x] Client
    * [x] Server
* [x] `delete` feature #15 
    * [x] API document and mock
    * [x] Client
    * [x] Server
* [x] `search` feature #16 
    * [x] API document and mock
    * [x] Client
    * [x] Server
